### ISSUE TITLE
Sidebar categories not expanding on docs site.

### ISSUE THREAD

**Issue by bhayward93** [cypress-io/cypress-documentation#2354] opened 2019-08-21 17:30 UTC
### Current behavior:

Links on the sidebar are note expanding to navigate content. Tested Chrome, Chromium and Firefox.

![image](https://user-images.githubusercontent.com/18596813/63453938-a912a300-c441-11e9-977a-ce7f8a6b39cf.png)

### Desired behavior:

Sidebar items should should expand on click.

### Steps to reproduce: (app code and test code)

Visit https://docs.cypress.io/guides/overview/why-cypress.html
Try to click a category on the sidebar, e.g. Getting Started

### Versions

Chrome, Chromium and Firefox

**Comment by MagedAhmad** [comment] 2020-01-13 01:22
It works fine for me ! (Firefox)

**Comment by CypressCecelia** [comment] 2020-02-18 21:36
@jennifer-shehane @bhayward93 I believe this is resolved, can you confirm if I'm missing something? Thanks!

**Comment by jennifer-shehane** [comment] 2020-02-19 08:29
Yah, I'm not sure I was able to reproduce this ever.

**Comment by CypressCecelia** [comment] 2020-02-19 16:17
Closing as unable to reproduce.

**Closed by CypressCecelia** 2020-02-19 16:17 UTC
Labels: first-timers-only, stage: ready for work, type: bug

**Comment by bhayward93** [comment] 2020-02-19 23:48
Hey, sorry for the lack of response; yeah it appears to be fixed properly for me

**Comment by bhayward93** [comment] 2020-02-19 23:49
Out of curiosity @CypressCecelia I was wondering if you knew where BrowserStack integration sits on your roadmap?
