### ISSUE TITLE
Invalid link to the repo for stubbing events from Electron

### ISSUE THREAD

**Issue by anupam-crownstack** [cypress-io/cypress-documentation#5282] opened 2023-06-01 10:08 UTC
### Description

The link is invalid which has code for stubbing events from Electron.

### URL of Issue(s)

https://docs.cypress.io/faq/questions/using-cypress-faq#Can-I-test-my-Electron-app

### Steps to replicate

1. Go to 'https://docs.cypress.io/faq/questions/using-cypress-faq#Can-I-test-my-Electron-app'
2. Click on 'here' at the bottom

![image](https://github.com/cypress-io/cypress-documentation/assets/84439035/802e4e96-4d75-4a3d-8780-4075e238af11)

### Device

- [x] PC
- [x] Mac
- [x] iPhone
- [x] iPad
- [x] Android Phone
- [x] Android Tablet

### Additional Information

This is path: https://github.com/cypress-io/cypress/tree/develop/packages/desktop-gui/cypress/integration

![image](https://github.com/cypress-io/cypress-documentation/assets/84439035/57eb877a-cf13-47a4-8b20-baddc16bc385)

**Comment by MikeMcC399** [comment] 2023-06-01 10:47
The link should probably be changed from
- https://github.com/cypress-io/cypress/tree/develop/packages/desktop-gui/cypress/integration to
- https://github.com/cypress-io/cypress/tree/develop/packages/launchpad/cypress/e2e

**Comment by AshwanthramKL** [comment] 2023-06-02 09:44
Hey @nagash77, can I work on this?

**Comment by MikeMcC399** [comment] 2023-06-02 10:13
@elylucas 

- This is a duplicate of https://github.com/cypress-io/cypress-documentation/issues/5131, so one of these two issues could be closed.

**Closed** 2023-06-05 13:19 UTC
Labels: type: bug, triaged
