### ISSUE TITLE
TypeScript Custom Command instructions incorrect

### ISSUE THREAD

**Issue by jethrolarson** [cypress-io/cypress-documentation#3773] opened 2021-03-31 20:17 UTC
## I'm submitting a...

```
[ ] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

The instructions here don't work right.
https://docs.cypress.io/guides/tooling/typescript-support#Types-for-custom-commands

They should be updated to match working examples like: https://github.com/omerose/cypress-support/blob/master/cypress/support/commands.ts#L29

**Comment by jennifer-shehane** [comment] 2021-05-03 17:02
Duplicate of https://github.com/cypress-io/cypress-documentation/issues/2565

**Closed by jennifer-shehane** 2021-05-03 17:02 UTC
