### ISSUE TITLE
Request: Add official WSL install documentation

### ISSUE THREAD

**Issue by vegerot** [cypress-io/cypress-documentation#3294] opened 2020-09-01 18:36 UTC
Not all of us can be Unix master race users.  I use Cypress on macOS with no issues, but some people on my team use WSL and I have had to do a lot of googling for them to figure out how to do it.  It would save us a lot of time to have some official documentation on this, where I can send devs to to figure out how to install Cypress on their machines

### Current behavior:

Installing Cypress on WSL is unintuitive and difficult

### Desired behavior:

Clear instructions on installing on WSL2

**Comment by jennifer-shehane** [comment] 2020-10-29 06:52
Duplicate of https://github.com/cypress-io/cypress-documentation/issues/2735

**Closed by jennifer-shehane** 2020-10-29 06:52 UTC
