### ISSUE TITLE
Docs Top Banner Update Failure

### ISSUE THREAD

**Issue by KateAbramova** [cypress-io/cypress-documentation#2315] opened 2019-12-16 16:47 UTC
## I'm submitting a...

```
[X] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

According to  https://github.com/contentful/contentful.js/issues/168, to cache the responses of Contentful, a cache proxy is needed, that way relevant data should be received in response to the request.
The part of the code responsible for the docs top banner during the build works without errors because it happens between NODE_ENV is: development and INFO Start processing (by the way, why development? https://circleci.com/gh/cypress-io/cypress-documentation/17980)
That is incorrect regarding the banner and belongs to master branch. There are no errors in it and there is development env for some reason.

In the process of building .html the skeleton of each page (layout?) is created, and the banner is a part of it - from this we can conclude that at the time of such an error (it is floating) html pages are not updated, or the data file is not overwritten. There should have been errors (there aren’t in the logs).
Based on the above, the conclusion (might not be the right one) that the issue is in the process of deployment / release to S3.
The screenshots of the logs of the failed deploy are attached
![2019-12-16 17 28 52](https://user-images.githubusercontent.com/49243310/70925735-6d28cc80-2034-11ea-8dbb-e4d2c6bb5904.jpg)
![2019-12-16 17 28 59](https://user-images.githubusercontent.com/49243310/70925742-6f8b2680-2034-11ea-8be6-d7760630b0d1.jpg)

gulp-awspublish package that’s being used together with gulpfile.js for publishing doesn’t contain errors as well

**Comment by amirrustam** [comment] 2019-12-16 17:30
@KateAbramova regarding NODE_ENV being set to `development` is just to initially build the docs for testing. Before it's deployed it's built with NODE_ENV `production` in the `deploy-docs-production` job: https://circleci.com/gh/cypress-io/cypress-documentation/18147

**Comment by amirrustam** [comment] 2019-12-16 17:34
@KateAbramova and @TonySynenko what is the proposed solution for proper handling of Contentful cache? I don't believe we even need a cache just for the banner. The content retrieval is fast enough, and it would get rid of issues like this.

**Comment by KateAbramova** [comment] 2019-12-17 14:08
@amirrustam since there's no cache proxy, the data received in response to request is always up-to-date. There's no cache for the docs top banner, so shouldn't be the issue.  
The build has been tested via a separate content_type: 'docsTopBanner2' with approx. 6-7 builds: content change and rebuild afterwards. Locally we couldn't replicate the failure and that leads to a conclusion that the issue is happening during deploy/release. 
Is there AWS log available for the date the banner failed to change on Prod? and also testing of the build /deploy on Prod.

**Comment by KateAbramova** [comment] 2019-12-17 14:17
> @KateAbramova regarding NODE_ENV being set to `development` is just to initially build the docs for testing. Before it's deployed it's built with NODE_ENV `production` in the `deploy-docs-production` job: https://circleci.com/gh/cypress-io/cypress-documentation/18147

There are 3 jobs: build, docs-tests, deploy-docs-production (https://circleci.com/gh/cypress-io/cypress-documentation/18147 - deploy-docs-production)

Based on this:
Before it's deployed it's built with NODE_ENV production in the deploy-docs-production job:

the issue could happen there and deploy to production.

Another question is why the build didn't fail if it didn't receive something

**Comment by amirrustam** [comment] 2019-12-17 16:35
We might be chasing a fluke here. The banner updates have been working since this issue was create, and that day Circle CI was being problematic in general. Closing now since we don't have any distinct and reproducible error to remedy.

**Closed by amirrustam** 2019-12-17 16:35 UTC
