### ISSUE TITLE
Improve Typescript documentation

### ISSUE THREAD

**Issue by stoplion** [cypress-io/cypress-documentation#3268] opened 2020-10-21 03:46 UTC
I've followed the docs here https://docs.cypress.io/api/cypress-api/custom-commands.html#See-also
and Typescript is not working.

Much of the issues are detailed here https://github.com/cypress-io/cypress-documentation/issues/2565

**Comment by jennifer-shehane** [comment] 2020-10-21 09:06
Duplicate of #2565.

**Closed by jennifer-shehane** 2020-10-21 09:06 UTC
