### ISSUE TITLE
Request: Official documentation on how to run on Windows Subsystem Linux (WSL)

### ISSUE THREAD

**Issue by JamesHenry** [cypress-io/cypress-documentation#2735] opened 2020-04-21 12:16 UTC
## I'm submitting a...

```
[ ] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

On the advice of @bahmutov on twitter opening this issue to request official documentation for running cypress on WSL, including accessing the GUI.

WSL is amazing technology, and it is a development environment that is growing fast in popularity, particularly at large Enterprises where developers have to use Windows machines by policy but still want the best from the *nix world.

My experience with trying to get cypress to run in this environment has been that it is just a case of chasing random error codes around the internet :) There are some unofficial blog posts out there on trying to get the GUI part to work with WSL but it is fiddly and does not seem to work with the latest versions of cypress.

Any help in this area would be much appreciated!

**Comment by amirrustam** [comment] 2021-03-11 05:19
Duplicate of #3022

**Closed by amirrustam** 2021-03-11 05:19 UTC
Labels: content: new
